version: '3.8'

services:
  web:
    image: ghcr.io/lamacheref/openindex_v2-web:latest
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: postgres:17
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: openindex
    volumes:
      - postgres_data:/var/lib/postgresql/data

  crawler:
    image: ghcr.io/lamacheref/openindex_v2-crawler:latest
    command: python src/smb_crawler_postgresql.py
    depends_on:
      - db

volumes:
  postgres_data:
